### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by laissezfarrell** [NCSU-Libraries/lentil#10]
Hi - 

Attempting to install Lentil, and get the following message(s) after running  bundle exec rails generate lentil:install:

_Run `bundle install` to install missing gems._

When running bundle install, I am returned the following:

_Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 3.2.16)

  In Gemfile:
    lentil (>= 0) x64-mingw32 depends on
      rails (~> 3.2.17) x64-mingw32

    rails (= 3.2.16) x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "jquery-rails":
  In snapshot (Gemfile.lock):
    jquery-rails (= 3.1.2)

  In Gemfile:
    lentil (>= 0) x64-mingw32 depends on
      jquery-rails (~> 2.3.0) x64-mingw32

    jquery-rails (>= 0) x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict._

I assume what I'm seeing is a result of working in Windows rather than a bug in the application, but any thoughts you have (known issues with certain platforms, etc.) would be helpful.

**Comment by cazzerson** [comment]
Hi Matthew,

Have you tried running `bundle update`? If that doesn't work, could you remove your Gemfile.lock and run it again?

**Comment by laissezfarrell** [comment]
Hey - 

I did try bundle update on Windows to no avail; I'll try the Gemfile.lock on that platform and report back.

I gave it a shot at installing on a Linux machine and the install handled fine after a bundle update.

**Comment by cazzerson** [comment]
Closing this, but let us know if you figured anything out.
