### ISSUE TITLE
engagement stats counts

### ISSUE THREAD

**Issue by mikenutt** [NCSU-Libraries/lentil#2]
[Feature request, doesn't look like I can add labels]

A dashboard in admin view could allow campaign administrators a quick way to see engagement stats and gauge the effectiveness of the campaign. Could include: 
-likes
-battles
-donor agreements
-visits (optional, could be viewed in Google Analytics instead)

**Comment by bretdavidson** [comment]
This has now been added! More information available in this commit: 7c06392631506a64f3d518df9b43475577e9d216
